services:
  starvlm:
    image: starvlm/startchat:1.0.0
    container_name: starchat
    depends_on:
      - db
    volumes:
      # Mount the storage directory to the container, for storing user files.
      - ./volumes/app/storage:/app/starchat/storage
    networks:
      - default
  db:
    image: postgres:15-alpine
    container_name: postgres-starchat
    environment:
      PGUSER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-starvlm}
      POSTGRES_DB: ${POSTGRES_DB:-starchat}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    command: >
      postgres -c 'max_connections=${POSTGRES_MAX_CONNECTIONS:-100}'
               -c 'shared_buffers=${POSTGRES_SHARED_BUFFERS:-128MB}'
               -c 'work_mem=${POSTGRES_WORK_MEM:-4MB}'
               -c 'maintenance_work_mem=${POSTGRES_MAINTENANCE_WORK_MEM:-64MB}'
               -c 'effective_cache_size=${POSTGRES_EFFECTIVE_CACHE_SIZE:-4096MB}'
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30